FORMAT: 1A
HOST: http://localhost

# Very Useful Tools to Remember para o Desafio BossaBox

#Group Authentication

## Authentication [/auth/google]

### Authenticate [POST]
+ Response 200 (application/json; charset=utf-8)
    + Attributes(Token)
+ Response 403 (application/json; charset=utf-8)
    + Attributes(Error)

# Group Tools

## Gerenciamento de ferramentas [/tools{?tag}]

### Listar ferramentas [GET]
+ Parameters
    + tag: node (string, optional) - Tag para refinar pesquisa.

+ Response 200 (application/json; charset=utf-8)
    + Attributes(array[ToolResponse])
+ Response 404 (application/json; charset=utf-8)
    + Attributes(Error)

## Gerenciamento de ferramentas [/tools]

### Cadastrar uma ferramenta [POST]
+ Request Criar ferramentas
    + Headers
    
            Accept: application/json
            Content-Type: application/json

    + Attributes(Tool)
+ Response 201 (application/json; charset=utf-8)
    + Attributes(ToolResponse)
+ Response 400 (application/json; charset=utf-8)
    + Attributes(Error)

## Gerenciamento de uma ferramenta [/tools/{id}]

### Remover uma ferramenta [DELETE]
+ Parameters
    + id: 1 (number, required) - ID da ferramenta

+ Response 202
+ Response 404 (application/json; charset=utf-8)
    + Attributes(Error)

# Data Structures
## Error (object)
+ code: 400 (number) - Codigo de retorno com valor default
+ message: Não Funcionou (string) - Mensagem de retorno
+ description: Erro ao executar a tarefa (string) - Descrição do erro

## Tool (object)
+ title: hotel (string) - Titulo da ferramenta
+ link: https://github.com/typicode/hotel (string) - URL da ferramenta
+ description: Local app manager. Start apps within your browser (string) - Descrição da ferramenta
+ tags: node (array[string]) - Tags da ferramenta

## ToolResponse (Tool)
+ id: 1 (number) - Identificador da ferramenta

## Token (object)
+ token: 73j3kd7dheo40sls= (string) - Token de autenticação